### ISSUE TITLE
Reorder variables in plot_corr()

### ISSUE THREAD

**Issue by OscarSmallenbroek** [bluefoxr/COINr#33] opened 2022-11-17 16:11 UTC
Hi Will, 

Currently, plot_corr() seems to order variables in alphabetical order. When doing statistical audits, we often want to present the correlations in a specific order - usually according to the pillar/sub-pillar structure.  Is there any way that we could specify a customized order. Otherwise, keeping the order the between plot_corr() and the dataframe the same would also work. 

Best, 
Oscar

**Comment by bluefoxr** [comment] 2022-11-18 09:33
HI Oscar, at the moment the plots *are* ordered according to the index structure, although they are alphabetically ordered inside each group. E.g. from the example:

![image](https://user-images.githubusercontent.com/72880276/202668943-f310ff7a-650c-4681-acc4-558a57a6ce12.png)

What order would you like exactly? The problem is that if you change the order, features such as the boxes and the grouping may not work, so this could be tricky to implement.

**Comment by OscarSmallenbroek** [comment] 2022-11-18 11:25
Hi William, 

Indeed, I meant ordering indicators within the index/pillar. For example, putting CO2 below Forest in your example. 

It would be a nice feature to have when creating a correlation plot between elements of an aggregate (e.g. indicators within one sub-pillar or sub-pillars within one pillar) and when plotting sub-pillars with pillars and the index, like in the plot below. 

```
plot_corr(EPI, dset = "Aggregated", iCodes  = list("ECO"),Levels = 2, flagcolours = FALSE,
          withparent= "family")
```
![image](https://user-images.githubusercontent.com/91374513/202693831-a74e2525-7e5b-4f21-a0c1-e1b7ce5672db.png)

**Comment by bluefoxr** [comment] 2022-11-18 14:55
Hi, I have added an option which lets you pass character vectors for the x and y axes ordering - see the `order_as` argument in `plot_corr()`. This should work as long as it is used carefully. Example:

```
coin <- build_example_coin()

plot_corr(coin, dset = "Normalised", iCodes = list("Political"), 
                order_as = list(c("IGOs", "Embs", "UNVote"), 
                                        c("Embs", "IGOs", "UNVote")))
```

see what you think.

**Comment by bluefoxr** [comment] 2022-11-18 14:56
Obviously you need to be aware of what codes will be present on the x and y axes, so you might need to plot with the default ordering first to be sure.

**Comment by bluefoxr** [comment] 2022-11-21 17:10
Presume this is fine so closing now.

**Closed by bluefoxr** 2022-11-21 17:10 UTC

**Comment by OscarSmallenbroek** [comment] 2022-11-21 17:14
Yes, thanks William.
